apiVersion: v1
kind: Service
metadata:
  name: go-hana-service
  labels:
    app: prometheus
spec:
  selector:
    app: go-hana-pod
  ports:
    - name: web
      protocol: TCP
      port: 9090
      targetPort: 9090